#!/usr/bin/python3

"""Driver package query/installation tool for NVIDIA GPUs on Linux"""

# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# Author: Alberto Milone <amilone@nvidia.com>

import os
import logging
import subprocess
import re
import json
import argparse
import sys


import DriverAssistant.detect


default_json_path = "/usr/share/driver-assistant/supported-gpus/supported-gpus.json"

# Make sure that the PATH environment variable is set
if not os.environ.get("PATH"):
    os.environ["PATH"] = "/sbin:/usr/sbin:/bin:/usr/bin"

instructions = {
    "amzn-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "amzn-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "debian-closed": ["sudo apt-get install -y cuda-drivers"],
    "debian-open": [
        "sudo apt-get install -y nvidia-kernel-open-dkms",
        "sudo apt-get install -y cuda-drivers",
    ],
    "fedora-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "fedora-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "mariner-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "mariner-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "kylin-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "kylin-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "opensuse-leap-closed": ["sudo zypper install -y cuda-drivers"],
    "opensuse-leap-open": [
        "sudo zypper install -y nvidia-open-driver-G06-kmp-default",
        "sudo zypper install -y cuda-drivers",
    ],
    "opensuse-tumbleweed-closed": ["sudo zypper install -y cuda-drivers"],
    "opensuse-tumbleweed-open": [
        "sudo zypper install -y nvidia-open-driver-G06-kmp-default",
        "sudo zypper install -y cuda-drivers",
    ],
    "sles-closed": ["sudo zypper install -y cuda-drivers"],
    "sles-open": [
        "sudo zypper install -y nvidia-open-driver-G06-kmp-default",
        "sudo zypper install -y cuda-drivers",
    ],
    "rhel-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "rhel-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "ubuntu-closed": ["sudo apt-get install -y cuda-drivers"],
    "ubuntu-open": [
        "sudo apt-get install -y nvidia-driver-BRANCH-open",
        "sudo apt-get install -y cuda-drivers-BRANCH",
    ],
}

### ADD CLEANUP INSTRUCTIONS? https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#switching-between-driver-module-flavors


def install_driver(driver, distro_id, version_id):
    print("Install driver")
    raise NotImplementedError
    # TODO
    # SHOW EULA and request consent


def print_instructions(driver, distro_id, version_id):
    #
    if distro_id == "opensuse":
        logging.debug()
        distro_id == "opensuse-leap"

    candidates = instructions.get("%s-%s" % (distro_id, driver))

    if not candidates:
        print(
            "Error: could not find the instructions for %s-%s" % (distro_id, driver),
            file=sys.stderr,
        )
        return False

    if distro_id == "ubuntu":
        # Check the available branch and pick the latest
        branch = DriverAssistant.detect.ubuntu_get_latest_driver_branch()
        if branch:
            it = 0
            for line in candidates:
                candidates[it] = line.replace("BRANCH", branch)
                it += 1
        else:
            print("Error: failed to get the latest driver branch", file=sys.stderr)
            return False

    print(
        "Please copy and paste the following command%s to install the %s kernel module flavour:"
        % ("s" if len(candidates) > 1 else "", "legacy" if driver == "closed" else "open")
    )
    for line in candidates:
        print("  %s" % line)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install the recommended driver",
        default=False,
    )
    parser.add_argument(
        "--supported-gpus",
        nargs="?",
        type=str,
        help="Use a different supported-gpus.json file",
    )
    parser.add_argument(
        "--sys-path",
        nargs="?",
        type=str,
        help="Use a different /sys path. Useful for testing",
    )
    parser.add_argument(
        "--os-release-path",
        nargs="?",
        type=str,
        help="Use a different path for the os-release file. Useful for testing",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="[OPTIONAL] Verbose output", default=False
    )
    args = parser.parse_args()

    needs_install = args.install
    supported_gpus = args.supported_gpus
    sys_path = args.sys_path
    os_release_path = args.os_release_path

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    driver = DriverAssistant.detect.recommend_driver(
        sys_path=sys_path, supported_gpus=supported_gpus
    )
    if not driver:
        print("Error: Failed to find a suitable driver", file=sys.stderr)
        exit(1)
    logging.debug("Recommended driver: %s" % driver)
    distro_id, version_id = DriverAssistant.detect.get_distro(os_release_path)
    if not distro_id:
        # print("Error: unsupported Linux distribution", file=sys.stderr)
        exit(1)
    logging.debug("OS detected: %s" % distro_id)
    if needs_install:
        install_driver(driver, distro_id, version_id)
    else:
        exit(0 if print_instructions(driver, distro_id, version_id) else 1)


if __name__ == "__main__":
    main()
