#!/usr/bin/python3

"""Driver package query/installation tool for NVIDIA GPUs on Linux"""

# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# Author: Alberto Milone <amilone@nvidia.com>

import os
import logging
import subprocess
import re
import json
import argparse
import sys


import NvidiaDriverAssistant.detect


default_directory = os.path.dirname(os.path.realpath(__file__))
default_json_path = os.path.join(default_directory, "supported-gpus", "supported-gpus.json")
install_json_path = "/usr/share/nvidia-driver-assistant/supported-gpus/supported-gpus.json"

# Make sure that the PATH environment variable is set
if not os.environ.get("PATH"):
    os.environ["PATH"] = "/sbin:/usr/sbin:/bin:/usr/bin"

instructions = {
    "amzn-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "amzn-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "debian-closed": ["sudo apt-get install -Vy cuda-drivers"],
    "debian-open": ["sudo apt-get install -Vy nvidia-open"],
    "fedora-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "fedora-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "azurelinux-closed": ["Not supported"],
    "azurelinux-open": ["sudo tdnf -y install nvidia-open"],
    "kylin-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "kylin-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "opensuse-closed": ["sudo zypper --verbose install -y cuda-drivers"],
    "opensuse-open": ["sudo zypper install nvidia-open"],
    "sles-closed": ["sudo zypper install -y cuda-drivers"],
    "sles-open": ["sudo zypper install -y nvidia-open"],
    "rhel-closed": ["sudo dnf -y module install nvidia-driver:latest-dkms"],
    "rhel-open": ["sudo dnf -y module install nvidia-driver:open-dkms"],
    "ubuntu-closed": ["sudo apt-get install -y cuda-drivers"],
    "ubuntu-open": ["sudo apt-get install -y nvidia-open"],
}

branch_instructions = {
    "amzn-closed": ["sudo dnf -y module install nvidia-driver:BRANCH-dkms"],
    "amzn-open": ["sudo dnf -y module install nvidia-driver:BRANCH-open"],
    "debian-closed": ["sudo apt-get install -Vy cuda-drivers-BRANCH"],
    "debian-open": ["sudo apt-get install -Vy nvidia-open-BRANCH"],
    "fedora-closed": ["sudo dnf -y module install nvidia-driver:BRANCH-dkms"],
    "fedora-open": ["sudo dnf -y module install nvidia-driver:BRANCH-open"],
    "azurelinux-closed": ["Not supported"],
    "azurelinux-open": ["sudo tdnf -y install nvidia-open-BRANCH"],
    "kylin-closed": ["sudo dnf -y module install nvidia-driver:BRANCH-dkms"],
    "kylin-open": ["sudo dnf -y module install nvidia-driver:BRANCH-open"],
    "opensuse-closed": ["sudo zypper --verbose install -y cuda-drivers-BRANCH"],
    "opensuse-open": ["sudo zypper install nvidia-open-BRANCH"],
    "sles-closed": ["sudo zypper install -y cuda-drivers-BRANCH"],
    "sles-open": ["sudo zypper install -y nvidia-open-BRANCH"],
    "rhel-closed": ["sudo dnf -y module install nvidia-driver:BRANCH-dkms"],
    "rhel-open": ["sudo dnf -y module install nvidia-driver:BRANCH-open"],
    "ubuntu-closed": ["sudo apt-get install -y cuda-drivers-BRANCH"],
    "ubuntu-open": ["sudo apt-get install -y nvidia-open-BRANCH"],
}

### ADD CLEANUP INSTRUCTIONS? https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#switching-between-driver-module-flavors


def process_results(driver, distro_id, version_id, branch_id=None, install=False):
    if branch_id:
        candidates = branch_instructions.get("%s-%s" % (distro_id, driver))
    else:
        candidates = instructions.get("%s-%s" % (distro_id, driver))

    if not candidates:
        print(
            "Error: could not find the instructions for %s-%s" % (distro_id, driver),
            file=sys.stderr,
        )
        return False

    if distro_id == "ubuntu" and not branch_id:
        # Check the available branch and pick the latest
        latest_branch = NvidiaDriverAssistant.detect.ubuntu_get_latest_driver_branch()
        if latest_branch:
            branch_id = latest_branch
        else:
            print("Error: failed to get the latest driver branch", file=sys.stderr)
            return False

    if branch_id:
        it = 0
        for line in candidates:
            candidates[it] = line.replace("BRANCH", branch_id)
            it += 1

    if install:
        print(
            "Installing the following package%s for the %s kernel module flavour:"
            % ("s" if len(candidates) > 1 else "", "legacy" if driver == "closed" else "open")
        )
        for line in candidates:
            print("  %s\n" % line)
            status = os.system(line)
            if status != 0:
                print(
                    "\nError: failed to execute the following command:\n  %s" % (line),
                    file=sys.stderr,
                )
                break
        return status == 0
    else:
        print(
            "Please copy and paste the following command%s to install the %s kernel module flavour:"
            % ("s" if len(candidates) > 1 else "", "legacy" if driver == "closed" else "open")
        )
        for line in candidates:
            print("  %s" % line)
    return True


def install_driver(driver, distro_id, version_id, branch_id=None):
    # Point users to the EULA
    print(
        "Using the NVIDIA driver implies acceptance of the NVIDIA Software\n"
        'License Agreement, contained in the "LICENSE" file in the\n'
        '"/usr/share/nvidia-driver-assistant/driver_eula" directory\n'
    )
    return process_results(driver, distro_id, version_id, branch_id=branch_id, install=True)


def print_instructions(driver, distro_id, version_id, branch_id=None):
    return process_results(driver, distro_id, version_id, branch_id=branch_id, install=False)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install the recommended driver",
        default=False,
    )
    parser.add_argument(
        "--branch",
        nargs="?",
        type=str,
        help="Specify a NVIDIA Driver branch",
    )
    parser.add_argument(
        "--supported-gpus",
        nargs="?",
        type=str,
        help="Use a different supported-gpus.json file",
    )
    parser.add_argument(
        "--sys-path",
        nargs="?",
        type=str,
        help="Use a different /sys path. Useful for testing",
    )
    parser.add_argument(
        "--os-release-path",
        nargs="?",
        type=str,
        help="Use a different path for the os-release file. Useful for testing",
    )
    parser.add_argument(
        "--distro",
        nargs="?",
        type=str,
        help='Specify a Linux distro using the "DISTRO:VERSION" or "DISTRO" pattern. Useful for testing',
    )
    parser.add_argument(
        "--module-flavor",
        nargs="?",
        type=str,
        help="Specify a kernel module flavor. Useful for testing",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="[OPTIONAL] Verbose output", default=False
    )
    args = parser.parse_args()

    needs_install = args.install
    branch_locked = args.branch
    supported_gpus = args.supported_gpus
    sys_path = args.sys_path
    os_release_path = args.os_release_path
    distro_override = args.distro
    module_override = args.module_flavor
    system_info = None

    if not supported_gpus:
        if os.path.isfile(install_json_path):
            supported_gpus = install_json_path
        elif os.path.isfile(default_json_path):
            supported_gpus = default_json_path

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    driver = NvidiaDriverAssistant.detect.recommend_driver(
        sys_path=sys_path, supported_gpus=supported_gpus
    )
    if not driver:
        print("Error: Failed to find a suitable driver", file=sys.stderr)
        exit(1)
    logging.debug("Recommended driver: %s" % driver)

    if module_override == "open":
        driver = "open"
    elif module_override == "closed":
        driver = "closed"

    if distro_override:
        system_info = NvidiaDriverAssistant.detect.override_distro(distro_override)
        print("Detected system:\n  %s %s\n" % (system_info.id, system_info.version_id))
    else:
        system_info = NvidiaDriverAssistant.detect.get_distro(os_release_path)

    if not system_info:
        # print("Error: unsupported Linux distribution", file=sys.stderr)
        exit(1)
    logging.debug("OS detected: %s" % system_info.id)
    if needs_install:
        install_driver(driver, system_info.id, system_info.version_id, branch_locked)
    else:
        exit(
            0
            if print_instructions(driver, system_info.id, system_info.version_id, branch_locked)
            else 1
        )


if __name__ == "__main__":
    main()
